import Head from 'next/head';
import { FormEvent, useState } from 'react';
import  { GradientBackground } from '../components/Layout';
import Footer from '../components/Footer'
import moment from 'moment';
import React from 'react';

export default function Form() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [group, setGroup] = useState('');
  const [message, setMessage] = useState('');
  const DateNow = moment().format('MMMM Do YYYY, h:mm:ss a');

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const form = {
      name,
      email,
      group,
      message,
      DateNow,
    };

    const response = await fetch('/api/submit', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(form),
    });

    //when done
    const content = await response.json();
    alert(content.data.tableRange);

    setName('');
    setEmail('');
    setGroup('');
    setMessage('');
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GradientBackground
        variant="large"
        className="fixed top-20 opacity-40 dark:opacity-60"
      />
      <div className='flex items-center justify-between mt-[-60px] mx-4'>
<div>
  <a href="/">

<button type="button" className=" mt-6 rotate-180 text-purple-500 border border-purple-500 hover:bg-purple-300 hover:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center dark:border-purple-400 dark:text-purple-300 dark:hover:text-white dark:focus:ring-blue-800">
  <svg aria-hidden="true" className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
  <span className="sr-only">Icon description</span>
</button>
  </a>
</div>
      <Footer  />
      </div>
   
      <main className=" min-h-screen mx-8 ">
        <div className="max-w-5xl mx-auto py-16">
         


          <div className="mt-10 sm:mt-0">
            <div className="md:grid md:grid-cols-3 md:gap-6">
              <div className="md:col-span-1">
                <div className="px-4 sm:px-0">
                  <h3 className="text-lg font-medium leading-6 ">
                    Form
                  </h3>
                  <p className="mt-1 text-sm " >
                  We're always looking for ways to improve this guide and make it as useful as possible. If you have any feedback, ideas, or suggestions, we would love to hear from you! 
                  </p>
                </div>
              </div>
              <div className="mt-5 md:col-span-2 md:mt-0">
                <form onSubmit={handleSubmit}>
                  <div className="overflow-hidden shadow sm:rounded-md">
                    <div className="bg-opacity-5 dark:bg-opacity-50 bg-black backdrop-blur-lg rounded drop-shadow-lg px-4 py-5 sm:p-6">
                      <div className="grid grid-cols-6 gap-6">
                        <div className="col-span-6 sm:col-span-4">
                          <label
                            htmlFor="name"
                            className="block text-sm font-medium"
                          >
                            First name
                          </label>
                          <input
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            type="text"
                            name="name"
                            id="name"
                            autoComplete="given-name"
                            className="mt-1 block w-full rounded-md opacity-90 border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                          />
                        </div>

                        {/* <div className="col-span-6 sm:col-span-3">
                          <label
                            htmlFor="last-name"
                            className="block text-sm font-medium "
                          >
                            Last name
                          </label>
                          <input
                            type="text"
                            name="last-name"
                            id="last-name"
                            autoComplete="family-name"
                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                          />
                        </div> */}

                        <div className="col-span-6 sm:col-span-4">
                          <label
                            htmlFor="email-address"
                            className="block text-sm font-medium "
                          >
                            Email address
                          </label>
                          <input
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            type="email"
                            name="email"
                            id="email"
                            autoComplete="email"
                            className="mt-1 block w-full rounded-md opacity-90 border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                          />
                        </div>

                        <div className="col-span-6 sm:col-span-3">
                          <label
                            htmlFor="country"
                            className="block text-sm font-medium "
                          >
                            Group №
                          </label>
                          <select
                           value={group}
                           onChange={(e) => setGroup(e.target.value)}
                           type="text"
                           name="group"
                           id="group"
                            autoComplete="country-name"
                            className="mt-1 block w-full rounded-md border opacity-90 border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                          >
                            <option>01</option>
                            <option>02</option>
                            <option>03</option>
                            <option>04</option>
                            <option>05</option>
                            <option>06</option>
                            <option>07</option>
                            <option>08</option>
                            <option>09</option>
                            <option>other</option>
                          </select>
                        </div>
                      </div>
                      <div className='mt-4 py-2 '>
                        <label
                          htmlFor="about"
                          className="  block text-sm font-medium "
                        >
                          About
                        </label>
                        <div className="mt-1">
                          <textarea
                            required
                            value={message}
                            onChange={(e) => setMessage(e.target.value)}
                            name="message"
                            id="message"
                            // rows="3"
                            className="mt-1 block w-full rounded-md opacity-90 border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                            placeholder="Wubba Lubba Dub dub!"
                          ></textarea>
                        </div>
                        <p className="mt-2 text-sm text-opacity-50">
                        Help us improve this guide.
                        </p>
                      </div>
                    </div>
                    <div className="bg-opacity-5 dark:bg-opacity-50 bg-black backdrop-blur-lg rounded drop-shadow-lg px-4 py-3 text-right sm:px-6">
                      <button
                        type="submit"
                        className="inline-flex justify-center  border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                      >
                        Submit
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
      {/* <GradientBackground
        variant="small"
        className="absolute bottom-0 opacity-20 dark:opacity-10"
      /> */}
    </div>
  );
}
